[package]
name = "sentry-core"
version = "0.18.0"
authors = ["Sentry <hello@sentry.io>"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/getsentry/sentry-rust"
homepage = "https://github.com/getsentry/sentry-rust"
documentation = "https://getsentry.github.io/sentry-rust"
description = """
Core sentry library used for instrumentation and integration development.
"""
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[features]
default = []
client = ["im", "rand"]
debug-to-log = ["log"]
test = []

[dependencies]
sentry-types = { version = "0.15.0", path = "../sentry-types" }
lazy_static = "1.4.0"
im = { version = "14.2.0", optional = true }
rand = { version = "0.7.3", optional = true }
log = { version = "0.4.8", optional = true, features = ["std"] }

[dev-dependencies]
thiserror = "1.0.15"
anyhow = "1.0.30"
failure = "0.1.8"
tokio = { version = "0.2", features = ["rt-core", "macros"] }
